language: python
env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/
jobs:
  include:
    - os: linux
      dist: focal
      env: BUILD_TYPE=deb
    - os: linux
      dist: focal
      env: BUILD_TYPE=opk
    - os: linux
      dist: focal
      env: BUILD_TYPE=wine_pyinstaller
#    - os: windows
#      language: bash
#      env: BUILD_TYPE=windows
    - os: linux
      dist: focal
      language: minimal
      env:
        - ANDROID_TOOLS=commandlinetools-linux-6609375_latest.zip
        - BUILD_TYPE=android
        - ANDROID_HOME=/usr/local/android_sdk
        - ANDROIDNDK=/usr/local/android_sdk/ndk_bundle"
        - ANDROIDAPI="27"  # SDK version
        - NDKAPI="21"
install:
  - if [ "$BUILD_TYPE" = "deb" ] && [ "$TRAVIS_DIST" = "bionic" ]; then buildconfig/install_bionic.sh ; fi
  - if [ "$BUILD_TYPE" = "deb" ] && [ "$TRAVIS_DIST" = "focal" ]; then buildconfig/install_focal.sh ; fi
  - if [ "$BUILD_TYPE" = "deb" ] && [ "$TRAVIS_DIST" = "xenial" ]; then buildconfig/install_xenial.sh ; fi
script:
  - mkdir build
  - if [ "$BUILD_TYPE" = "android" ]; then buildconfig/build_android.sh ; fi
  - if [ "$BUILD_TYPE" = "deb" ]; then buildconfig/build_deb.sh ; fi
  - if [ "$BUILD_TYPE" = "flatpak" ]; then buildconfig/build_flatpak.sh ; fi
  - if [ "$BUILD_TYPE" = "opk" ]; then buildconfig/build_opk.sh ; fi
  - if [ "$BUILD_TYPE" = "windows" ]; then travis_wait 15 buildconfig/build_windows.sh ; fi
  - if [ "$BUILD_TYPE" = "wine_pyinstaller" ]; then buildconfig/build_wine_pyinstaller.sh ; fi
deploy:
  provider: releases
  api_key:
    secure: LbDce8fi3QChPRBzM36o7m26IdQ9PySPE6kKXnNK4KrpdzZ5gzBpc/ak4omWKcN5x2XFgzIH075ykEpKiYQP764hvYO3hGi+IcHEzW9A1FofP2Whl/qOLFpmA+afnhl7Uyw4Uo8mo27UUDwrPIrkjIlLW2PPUSiMDVhz6t28cQAsBXcMOBTrDuRFCtUHmkODFq6o6IEbkeoG7eVC/LFVLxO4zGHcxcJCyl6ar1GD9wznFxDomtyQiT7Xwxw9DpzHWUgdPCpYULBvTU+GBTMMQVKPZLROFwmdWy/VMCo9VfmITNNe0EBX7OQWel8CjIZAdqa04bWz23HiTvmvaPnWDYWykCUl/FEy9y6akl/aBhOLCtI2VeKO1jI6jYWQsjI+z4P1zcTBio/xfhwqk7E5a6OesmZLCwLSwyK9R8dtUYdCzp602hkPvxmyWA61gHtsPttROoLmaD+VLIVbvjmkohXqLp72vsgzDIFz59S+19DoBTUmh4kWVSWH9hrG72ynSwl+9RNHTbAlXCZhUNQktBNWCQSltAndyzNCjU0WCohmj2uFJDa0LyIOkE27G8BmwyQ+mRpOp8KByKgawUWXOjYPD5J1gs5X9fHtMdPKWbn4MIaQy66jBj0+lFwxwX2/5J7T3MuRRuxfHzw7GQS+MzrctgRF4s3c6mEAHypAK2Q=
  file_glob: true
  file: build/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: Tuxemon/Tuxemon
    branch: development
